controller_list:
  - name: fake_arm_controller
    joints:
      - drive1_joint
      - drive2_joint
      - drive3_joint
      - drive4_joint
      - drive5_joint
      - drive6_joint
  - name: fake_hand_controller
    joints:
      - pincer_joint