# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: home
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - drive1_joint
    - drive2_joint
    - drive3_joint
    - drive4_joint
    - drive5_joint
    - drive6_joint
    - pincer_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - drive1_joint
      - drive2_joint
      - drive3_joint
      - drive4_joint
      - drive5_joint
      - drive6_joint
  - name: hand_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      pincer_joint
arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - drive1_joint
    - drive2_joint
    - drive3_joint
    - drive4_joint
    - drive5_joint
    - drive6_joint
  gains:
    drive1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    drive2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    drive3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    drive4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    drive5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    drive6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

hand_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    - pincer_joint
  gains:
    pincer_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
      
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
    - drive1_joint
    - drive2_joint
    - drive3_joint
    - drive4_joint
    - drive5_joint
    - drive6_joint